global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fraud-ach-metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9092']
